/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedPluginsRouteImport } from './routes/_authenticated/plugins'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAccountAccessibilityRouteImport } from './routes/_authenticated/account/accessibility'
import { Route as AuthenticatedAccountAnnouncementsRouteImport } from './routes/_authenticated/account/announcements'
import { Route as AuthenticatedAccountEportfoliosRouteImport } from './routes/_authenticated/account/eportfolios'
import { Route as AuthenticatedAccountFilesRouteImport } from './routes/_authenticated/account/files'
import { Route as AuthenticatedAccountNotificationsRouteImport } from './routes/_authenticated/account/notifications'
import { Route as AuthenticatedAccountPortfolioRouteImport } from './routes/_authenticated/account/portfolio'
import { Route as AuthenticatedAccountProfileRouteImport } from './routes/_authenticated/account/profile'
import { Route as AuthenticatedAccountQrRouteImport } from './routes/_authenticated/account/qr'
import { Route as AuthenticatedAccountSharedRouteImport } from './routes/_authenticated/account/shared'
import { Route as AuthenticatedAgentIndexRouteImport } from './routes/_authenticated/agent/index'
import { Route as AuthenticatedAgentChatIdRouteImport } from './routes/_authenticated/agent/$chatId'
import { Route as AuthenticatedAgentActivityRouteImport } from './routes/_authenticated/agent/activity'
import { Route as AuthenticatedCanvasIndexRouteImport } from './routes/_authenticated/canvas/index'
import { Route as AuthenticatedCanvasCanvasIdRouteImport } from './routes/_authenticated/canvas/$canvasId'
import { Route as AuthenticatedCoursesIndexRouteImport } from './routes/_authenticated/courses/index'
import { Route as AuthenticatedCoursesCourseIdRouteRouteImport } from './routes/_authenticated/courses/$courseId/route'
import { Route as AuthenticatedNotesIndexRouteImport } from './routes/_authenticated/notes/index'
import { Route as AuthenticatedNotesNoteIdRouteImport } from './routes/_authenticated/notes/$noteId'
import { Route as AuthenticatedNotesGraphRouteImport } from './routes/_authenticated/notes/graph'
import { Route as OauthGoogleReturnRouteImport } from './routes/oauth/google/return'
import { Route as AuthenticatedCoursesCourseIdIndexRouteImport } from './routes/_authenticated/courses/$courseId/index'
import { Route as AuthenticatedCoursesCourseIdAnnouncementsRouteImport } from './routes/_authenticated/courses/$courseId/announcements'
import { Route as AuthenticatedCoursesCourseIdDiscussionsRouteImport } from './routes/_authenticated/courses/$courseId/discussions'
import { Route as AuthenticatedCoursesCourseIdIgniteRouteImport } from './routes/_authenticated/courses/$courseId/ignite'
import { Route as AuthenticatedCoursesCourseIdModulesRouteImport } from './routes/_authenticated/courses/$courseId/modules'
import { Route as AuthenticatedCoursesCourseIdPeopleRouteImport } from './routes/_authenticated/courses/$courseId/people'
import { Route as AuthenticatedCoursesCourseIdProgressRouteImport } from './routes/_authenticated/courses/$courseId/progress'
import { Route as AuthenticatedCoursesCourseIdQuizzesRouteImport } from './routes/_authenticated/courses/$courseId/quizzes'
import { Route as AuthenticatedCoursesCourseIdRubricsRouteImport } from './routes/_authenticated/courses/$courseId/rubrics'
import { Route as AuthenticatedCoursesCourseIdSettingsRouteImport } from './routes/_authenticated/courses/$courseId/settings'
import { Route as AuthenticatedCoursesCourseIdSyllabusRouteImport } from './routes/_authenticated/courses/$courseId/syllabus'
import { Route as AuthenticatedCoursesCourseIdAssignmentsIndexRouteImport } from './routes/_authenticated/courses/$courseId/assignments/index'
import { Route as AuthenticatedCoursesCourseIdAssignmentsAssignmentIdRouteImport } from './routes/_authenticated/courses/$courseId/assignments/$assignmentId'
import { Route as AuthenticatedCoursesCourseIdToolsToolIdRouteImport } from './routes/_authenticated/courses/$courseId/tools/$toolId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPluginsRoute = AuthenticatedPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccountAccessibilityRoute =
  AuthenticatedAccountAccessibilityRouteImport.update({
    id: '/account/accessibility',
    path: '/account/accessibility',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountAnnouncementsRoute =
  AuthenticatedAccountAnnouncementsRouteImport.update({
    id: '/account/announcements',
    path: '/account/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountEportfoliosRoute =
  AuthenticatedAccountEportfoliosRouteImport.update({
    id: '/account/eportfolios',
    path: '/account/eportfolios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountFilesRoute =
  AuthenticatedAccountFilesRouteImport.update({
    id: '/account/files',
    path: '/account/files',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountNotificationsRoute =
  AuthenticatedAccountNotificationsRouteImport.update({
    id: '/account/notifications',
    path: '/account/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountPortfolioRoute =
  AuthenticatedAccountPortfolioRouteImport.update({
    id: '/account/portfolio',
    path: '/account/portfolio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountProfileRoute =
  AuthenticatedAccountProfileRouteImport.update({
    id: '/account/profile',
    path: '/account/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountQrRoute = AuthenticatedAccountQrRouteImport.update({
  id: '/account/qr',
  path: '/account/qr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountSharedRoute =
  AuthenticatedAccountSharedRouteImport.update({
    id: '/account/shared',
    path: '/account/shared',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentIndexRoute = AuthenticatedAgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentChatIdRoute =
  AuthenticatedAgentChatIdRouteImport.update({
    id: '/agent/$chatId',
    path: '/agent/$chatId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentActivityRoute =
  AuthenticatedAgentActivityRouteImport.update({
    id: '/agent/activity',
    path: '/agent/activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCanvasIndexRoute =
  AuthenticatedCanvasIndexRouteImport.update({
    id: '/canvas/',
    path: '/canvas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCanvasCanvasIdRoute =
  AuthenticatedCanvasCanvasIdRouteImport.update({
    id: '/canvas/$canvasId',
    path: '/canvas/$canvasId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesIndexRoute =
  AuthenticatedCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdRouteRoute =
  AuthenticatedCoursesCourseIdRouteRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotesIndexRoute = AuthenticatedNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesNoteIdRoute =
  AuthenticatedNotesNoteIdRouteImport.update({
    id: '/notes/$noteId',
    path: '/notes/$noteId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotesGraphRoute = AuthenticatedNotesGraphRouteImport.update({
  id: '/notes/graph',
  path: '/notes/graph',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OauthGoogleReturnRoute = OauthGoogleReturnRouteImport.update({
  id: '/oauth/google/return',
  path: '/oauth/google/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoursesCourseIdIndexRoute =
  AuthenticatedCoursesCourseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCoursesCourseIdRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdAnnouncementsRoute =
  AuthenticatedCoursesCourseIdAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedCoursesCourseIdRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdDiscussionsRoute =
  AuthenticatedCoursesCourseIdDiscussionsRouteImport.update({
    id: '/discussions',
    path: '/discussions',
    getParentRoute: () => AuthenticatedCoursesCourseIdRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdIgniteRoute =
  AuthenticatedCoursesCourseIdIgniteRouteImport.update({
    id: '/ignite',
    path: '/ignite',
    getParentRoute: () => AuthenticatedCoursesCourseIdRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdModulesRoute =
  AuthenticatedCoursesCourseIdModulesRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => AuthenticatedCoursesCourseIdRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdPeopleRoute =
  AuthenticatedCoursesCourseIdPeopleRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => AuthenticatedCoursesCourseIdRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdProgressRoute =
  AuthenticatedCoursesCourseIdProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AuthenticatedCoursesCourseIdRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdQuizzesRoute =
  AuthenticatedCoursesCourseIdQuizzesRouteImport.update({
    id: '/quizzes',
    path: '/quizzes',
    getParentRoute: () => AuthenticatedCoursesCourseIdRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdRubricsRoute =
  AuthenticatedCoursesCourseIdRubricsRouteImport.update({
    id: '/rubrics',
    path: '/rubrics',
    getParentRoute: () => AuthenticatedCoursesCourseIdRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdSettingsRoute =
  AuthenticatedCoursesCourseIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCoursesCourseIdRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdSyllabusRoute =
  AuthenticatedCoursesCourseIdSyllabusRouteImport.update({
    id: '/syllabus',
    path: '/syllabus',
    getParentRoute: () => AuthenticatedCoursesCourseIdRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdAssignmentsIndexRoute =
  AuthenticatedCoursesCourseIdAssignmentsIndexRouteImport.update({
    id: '/assignments/',
    path: '/assignments/',
    getParentRoute: () => AuthenticatedCoursesCourseIdRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdAssignmentsAssignmentIdRoute =
  AuthenticatedCoursesCourseIdAssignmentsAssignmentIdRouteImport.update({
    id: '/assignments/$assignmentId',
    path: '/assignments/$assignmentId',
    getParentRoute: () => AuthenticatedCoursesCourseIdRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdToolsToolIdRoute =
  AuthenticatedCoursesCourseIdToolsToolIdRouteImport.update({
    id: '/tools/$toolId',
    path: '/tools/$toolId',
    getParentRoute: () => AuthenticatedCoursesCourseIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/plugins': typeof AuthenticatedPluginsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/student': typeof AuthenticatedStudentRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRouteRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/account/accessibility': typeof AuthenticatedAccountAccessibilityRoute
  '/account/announcements': typeof AuthenticatedAccountAnnouncementsRoute
  '/account/eportfolios': typeof AuthenticatedAccountEportfoliosRoute
  '/account/files': typeof AuthenticatedAccountFilesRoute
  '/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/account/portfolio': typeof AuthenticatedAccountPortfolioRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/qr': typeof AuthenticatedAccountQrRoute
  '/account/shared': typeof AuthenticatedAccountSharedRoute
  '/agent/$chatId': typeof AuthenticatedAgentChatIdRoute
  '/agent/activity': typeof AuthenticatedAgentActivityRoute
  '/canvas/$canvasId': typeof AuthenticatedCanvasCanvasIdRoute
  '/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute
  '/notes/graph': typeof AuthenticatedNotesGraphRoute
  '/oauth/google/return': typeof OauthGoogleReturnRoute
  '/agent/': typeof AuthenticatedAgentIndexRoute
  '/canvas/': typeof AuthenticatedCanvasIndexRoute
  '/courses/': typeof AuthenticatedCoursesIndexRoute
  '/notes/': typeof AuthenticatedNotesIndexRoute
  '/courses/$courseId/announcements': typeof AuthenticatedCoursesCourseIdAnnouncementsRoute
  '/courses/$courseId/discussions': typeof AuthenticatedCoursesCourseIdDiscussionsRoute
  '/courses/$courseId/ignite': typeof AuthenticatedCoursesCourseIdIgniteRoute
  '/courses/$courseId/modules': typeof AuthenticatedCoursesCourseIdModulesRoute
  '/courses/$courseId/people': typeof AuthenticatedCoursesCourseIdPeopleRoute
  '/courses/$courseId/progress': typeof AuthenticatedCoursesCourseIdProgressRoute
  '/courses/$courseId/quizzes': typeof AuthenticatedCoursesCourseIdQuizzesRoute
  '/courses/$courseId/rubrics': typeof AuthenticatedCoursesCourseIdRubricsRoute
  '/courses/$courseId/settings': typeof AuthenticatedCoursesCourseIdSettingsRoute
  '/courses/$courseId/syllabus': typeof AuthenticatedCoursesCourseIdSyllabusRoute
  '/courses/$courseId/': typeof AuthenticatedCoursesCourseIdIndexRoute
  '/courses/$courseId/assignments/$assignmentId': typeof AuthenticatedCoursesCourseIdAssignmentsAssignmentIdRoute
  '/courses/$courseId/tools/$toolId': typeof AuthenticatedCoursesCourseIdToolsToolIdRoute
  '/courses/$courseId/assignments/': typeof AuthenticatedCoursesCourseIdAssignmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/plugins': typeof AuthenticatedPluginsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/student': typeof AuthenticatedStudentRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/account/accessibility': typeof AuthenticatedAccountAccessibilityRoute
  '/account/announcements': typeof AuthenticatedAccountAnnouncementsRoute
  '/account/eportfolios': typeof AuthenticatedAccountEportfoliosRoute
  '/account/files': typeof AuthenticatedAccountFilesRoute
  '/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/account/portfolio': typeof AuthenticatedAccountPortfolioRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/qr': typeof AuthenticatedAccountQrRoute
  '/account/shared': typeof AuthenticatedAccountSharedRoute
  '/agent/$chatId': typeof AuthenticatedAgentChatIdRoute
  '/agent/activity': typeof AuthenticatedAgentActivityRoute
  '/canvas/$canvasId': typeof AuthenticatedCanvasCanvasIdRoute
  '/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute
  '/notes/graph': typeof AuthenticatedNotesGraphRoute
  '/oauth/google/return': typeof OauthGoogleReturnRoute
  '/agent': typeof AuthenticatedAgentIndexRoute
  '/canvas': typeof AuthenticatedCanvasIndexRoute
  '/courses': typeof AuthenticatedCoursesIndexRoute
  '/notes': typeof AuthenticatedNotesIndexRoute
  '/courses/$courseId/announcements': typeof AuthenticatedCoursesCourseIdAnnouncementsRoute
  '/courses/$courseId/discussions': typeof AuthenticatedCoursesCourseIdDiscussionsRoute
  '/courses/$courseId/ignite': typeof AuthenticatedCoursesCourseIdIgniteRoute
  '/courses/$courseId/modules': typeof AuthenticatedCoursesCourseIdModulesRoute
  '/courses/$courseId/people': typeof AuthenticatedCoursesCourseIdPeopleRoute
  '/courses/$courseId/progress': typeof AuthenticatedCoursesCourseIdProgressRoute
  '/courses/$courseId/quizzes': typeof AuthenticatedCoursesCourseIdQuizzesRoute
  '/courses/$courseId/rubrics': typeof AuthenticatedCoursesCourseIdRubricsRoute
  '/courses/$courseId/settings': typeof AuthenticatedCoursesCourseIdSettingsRoute
  '/courses/$courseId/syllabus': typeof AuthenticatedCoursesCourseIdSyllabusRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdIndexRoute
  '/courses/$courseId/assignments/$assignmentId': typeof AuthenticatedCoursesCourseIdAssignmentsAssignmentIdRoute
  '/courses/$courseId/tools/$toolId': typeof AuthenticatedCoursesCourseIdToolsToolIdRoute
  '/courses/$courseId/assignments': typeof AuthenticatedCoursesCourseIdAssignmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/plugins': typeof AuthenticatedPluginsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/student': typeof AuthenticatedStudentRoute
  '/_authenticated/courses/$courseId': typeof AuthenticatedCoursesCourseIdRouteRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/account/accessibility': typeof AuthenticatedAccountAccessibilityRoute
  '/_authenticated/account/announcements': typeof AuthenticatedAccountAnnouncementsRoute
  '/_authenticated/account/eportfolios': typeof AuthenticatedAccountEportfoliosRoute
  '/_authenticated/account/files': typeof AuthenticatedAccountFilesRoute
  '/_authenticated/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/_authenticated/account/portfolio': typeof AuthenticatedAccountPortfolioRoute
  '/_authenticated/account/profile': typeof AuthenticatedAccountProfileRoute
  '/_authenticated/account/qr': typeof AuthenticatedAccountQrRoute
  '/_authenticated/account/shared': typeof AuthenticatedAccountSharedRoute
  '/_authenticated/agent/$chatId': typeof AuthenticatedAgentChatIdRoute
  '/_authenticated/agent/activity': typeof AuthenticatedAgentActivityRoute
  '/_authenticated/canvas/$canvasId': typeof AuthenticatedCanvasCanvasIdRoute
  '/_authenticated/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute
  '/_authenticated/notes/graph': typeof AuthenticatedNotesGraphRoute
  '/oauth/google/return': typeof OauthGoogleReturnRoute
  '/_authenticated/agent/': typeof AuthenticatedAgentIndexRoute
  '/_authenticated/canvas/': typeof AuthenticatedCanvasIndexRoute
  '/_authenticated/courses/': typeof AuthenticatedCoursesIndexRoute
  '/_authenticated/notes/': typeof AuthenticatedNotesIndexRoute
  '/_authenticated/courses/$courseId/announcements': typeof AuthenticatedCoursesCourseIdAnnouncementsRoute
  '/_authenticated/courses/$courseId/discussions': typeof AuthenticatedCoursesCourseIdDiscussionsRoute
  '/_authenticated/courses/$courseId/ignite': typeof AuthenticatedCoursesCourseIdIgniteRoute
  '/_authenticated/courses/$courseId/modules': typeof AuthenticatedCoursesCourseIdModulesRoute
  '/_authenticated/courses/$courseId/people': typeof AuthenticatedCoursesCourseIdPeopleRoute
  '/_authenticated/courses/$courseId/progress': typeof AuthenticatedCoursesCourseIdProgressRoute
  '/_authenticated/courses/$courseId/quizzes': typeof AuthenticatedCoursesCourseIdQuizzesRoute
  '/_authenticated/courses/$courseId/rubrics': typeof AuthenticatedCoursesCourseIdRubricsRoute
  '/_authenticated/courses/$courseId/settings': typeof AuthenticatedCoursesCourseIdSettingsRoute
  '/_authenticated/courses/$courseId/syllabus': typeof AuthenticatedCoursesCourseIdSyllabusRoute
  '/_authenticated/courses/$courseId/': typeof AuthenticatedCoursesCourseIdIndexRoute
  '/_authenticated/courses/$courseId/assignments/$assignmentId': typeof AuthenticatedCoursesCourseIdAssignmentsAssignmentIdRoute
  '/_authenticated/courses/$courseId/tools/$toolId': typeof AuthenticatedCoursesCourseIdToolsToolIdRoute
  '/_authenticated/courses/$courseId/assignments/': typeof AuthenticatedCoursesCourseIdAssignmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/onboarding'
    | '/privacy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/calendar'
    | '/dashboard'
    | '/help'
    | '/history'
    | '/inbox'
    | '/meetings'
    | '/members'
    | '/plugins'
    | '/settings'
    | '/student'
    | '/courses/$courseId'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/account/accessibility'
    | '/account/announcements'
    | '/account/eportfolios'
    | '/account/files'
    | '/account/notifications'
    | '/account/portfolio'
    | '/account/profile'
    | '/account/qr'
    | '/account/shared'
    | '/agent/$chatId'
    | '/agent/activity'
    | '/canvas/$canvasId'
    | '/notes/$noteId'
    | '/notes/graph'
    | '/oauth/google/return'
    | '/agent/'
    | '/canvas/'
    | '/courses/'
    | '/notes/'
    | '/courses/$courseId/announcements'
    | '/courses/$courseId/discussions'
    | '/courses/$courseId/ignite'
    | '/courses/$courseId/modules'
    | '/courses/$courseId/people'
    | '/courses/$courseId/progress'
    | '/courses/$courseId/quizzes'
    | '/courses/$courseId/rubrics'
    | '/courses/$courseId/settings'
    | '/courses/$courseId/syllabus'
    | '/courses/$courseId/'
    | '/courses/$courseId/assignments/$assignmentId'
    | '/courses/$courseId/tools/$toolId'
    | '/courses/$courseId/assignments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/onboarding'
    | '/privacy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/calendar'
    | '/dashboard'
    | '/help'
    | '/history'
    | '/inbox'
    | '/meetings'
    | '/members'
    | '/plugins'
    | '/settings'
    | '/student'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/account/accessibility'
    | '/account/announcements'
    | '/account/eportfolios'
    | '/account/files'
    | '/account/notifications'
    | '/account/portfolio'
    | '/account/profile'
    | '/account/qr'
    | '/account/shared'
    | '/agent/$chatId'
    | '/agent/activity'
    | '/canvas/$canvasId'
    | '/notes/$noteId'
    | '/notes/graph'
    | '/oauth/google/return'
    | '/agent'
    | '/canvas'
    | '/courses'
    | '/notes'
    | '/courses/$courseId/announcements'
    | '/courses/$courseId/discussions'
    | '/courses/$courseId/ignite'
    | '/courses/$courseId/modules'
    | '/courses/$courseId/people'
    | '/courses/$courseId/progress'
    | '/courses/$courseId/quizzes'
    | '/courses/$courseId/rubrics'
    | '/courses/$courseId/settings'
    | '/courses/$courseId/syllabus'
    | '/courses/$courseId'
    | '/courses/$courseId/assignments/$assignmentId'
    | '/courses/$courseId/tools/$toolId'
    | '/courses/$courseId/assignments'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/onboarding'
    | '/privacy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/help'
    | '/_authenticated/history'
    | '/_authenticated/inbox'
    | '/_authenticated/meetings'
    | '/_authenticated/members'
    | '/_authenticated/plugins'
    | '/_authenticated/settings'
    | '/_authenticated/student'
    | '/_authenticated/courses/$courseId'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/account/accessibility'
    | '/_authenticated/account/announcements'
    | '/_authenticated/account/eportfolios'
    | '/_authenticated/account/files'
    | '/_authenticated/account/notifications'
    | '/_authenticated/account/portfolio'
    | '/_authenticated/account/profile'
    | '/_authenticated/account/qr'
    | '/_authenticated/account/shared'
    | '/_authenticated/agent/$chatId'
    | '/_authenticated/agent/activity'
    | '/_authenticated/canvas/$canvasId'
    | '/_authenticated/notes/$noteId'
    | '/_authenticated/notes/graph'
    | '/oauth/google/return'
    | '/_authenticated/agent/'
    | '/_authenticated/canvas/'
    | '/_authenticated/courses/'
    | '/_authenticated/notes/'
    | '/_authenticated/courses/$courseId/announcements'
    | '/_authenticated/courses/$courseId/discussions'
    | '/_authenticated/courses/$courseId/ignite'
    | '/_authenticated/courses/$courseId/modules'
    | '/_authenticated/courses/$courseId/people'
    | '/_authenticated/courses/$courseId/progress'
    | '/_authenticated/courses/$courseId/quizzes'
    | '/_authenticated/courses/$courseId/rubrics'
    | '/_authenticated/courses/$courseId/settings'
    | '/_authenticated/courses/$courseId/syllabus'
    | '/_authenticated/courses/$courseId/'
    | '/_authenticated/courses/$courseId/assignments/$assignmentId'
    | '/_authenticated/courses/$courseId/tools/$toolId'
    | '/_authenticated/courses/$courseId/assignments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  OauthGoogleReturnRoute: typeof OauthGoogleReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plugins': {
      id: '/_authenticated/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof AuthenticatedPluginsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/accessibility': {
      id: '/_authenticated/account/accessibility'
      path: '/account/accessibility'
      fullPath: '/account/accessibility'
      preLoaderRoute: typeof AuthenticatedAccountAccessibilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/announcements': {
      id: '/_authenticated/account/announcements'
      path: '/account/announcements'
      fullPath: '/account/announcements'
      preLoaderRoute: typeof AuthenticatedAccountAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/eportfolios': {
      id: '/_authenticated/account/eportfolios'
      path: '/account/eportfolios'
      fullPath: '/account/eportfolios'
      preLoaderRoute: typeof AuthenticatedAccountEportfoliosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/files': {
      id: '/_authenticated/account/files'
      path: '/account/files'
      fullPath: '/account/files'
      preLoaderRoute: typeof AuthenticatedAccountFilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/notifications': {
      id: '/_authenticated/account/notifications'
      path: '/account/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AuthenticatedAccountNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/portfolio': {
      id: '/_authenticated/account/portfolio'
      path: '/account/portfolio'
      fullPath: '/account/portfolio'
      preLoaderRoute: typeof AuthenticatedAccountPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/profile': {
      id: '/_authenticated/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AuthenticatedAccountProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/qr': {
      id: '/_authenticated/account/qr'
      path: '/account/qr'
      fullPath: '/account/qr'
      preLoaderRoute: typeof AuthenticatedAccountQrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/shared': {
      id: '/_authenticated/account/shared'
      path: '/account/shared'
      fullPath: '/account/shared'
      preLoaderRoute: typeof AuthenticatedAccountSharedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent/': {
      id: '/_authenticated/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AuthenticatedAgentIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent/$chatId': {
      id: '/_authenticated/agent/$chatId'
      path: '/agent/$chatId'
      fullPath: '/agent/$chatId'
      preLoaderRoute: typeof AuthenticatedAgentChatIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent/activity': {
      id: '/_authenticated/agent/activity'
      path: '/agent/activity'
      fullPath: '/agent/activity'
      preLoaderRoute: typeof AuthenticatedAgentActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/canvas/': {
      id: '/_authenticated/canvas/'
      path: '/canvas'
      fullPath: '/canvas/'
      preLoaderRoute: typeof AuthenticatedCanvasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/canvas/$canvasId': {
      id: '/_authenticated/canvas/$canvasId'
      path: '/canvas/$canvasId'
      fullPath: '/canvas/$canvasId'
      preLoaderRoute: typeof AuthenticatedCanvasCanvasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/': {
      id: '/_authenticated/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AuthenticatedCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$courseId': {
      id: '/_authenticated/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes/': {
      id: '/_authenticated/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof AuthenticatedNotesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes/$noteId': {
      id: '/_authenticated/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AuthenticatedNotesNoteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes/graph': {
      id: '/_authenticated/notes/graph'
      path: '/notes/graph'
      fullPath: '/notes/graph'
      preLoaderRoute: typeof AuthenticatedNotesGraphRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/oauth/google/return': {
      id: '/oauth/google/return'
      path: '/oauth/google/return'
      fullPath: '/oauth/google/return'
      preLoaderRoute: typeof OauthGoogleReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/courses/$courseId/': {
      id: '/_authenticated/courses/$courseId/'
      path: '/'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdIndexRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRouteRoute
    }
    '/_authenticated/courses/$courseId/announcements': {
      id: '/_authenticated/courses/$courseId/announcements'
      path: '/announcements'
      fullPath: '/courses/$courseId/announcements'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRouteRoute
    }
    '/_authenticated/courses/$courseId/discussions': {
      id: '/_authenticated/courses/$courseId/discussions'
      path: '/discussions'
      fullPath: '/courses/$courseId/discussions'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdDiscussionsRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRouteRoute
    }
    '/_authenticated/courses/$courseId/ignite': {
      id: '/_authenticated/courses/$courseId/ignite'
      path: '/ignite'
      fullPath: '/courses/$courseId/ignite'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdIgniteRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRouteRoute
    }
    '/_authenticated/courses/$courseId/modules': {
      id: '/_authenticated/courses/$courseId/modules'
      path: '/modules'
      fullPath: '/courses/$courseId/modules'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdModulesRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRouteRoute
    }
    '/_authenticated/courses/$courseId/people': {
      id: '/_authenticated/courses/$courseId/people'
      path: '/people'
      fullPath: '/courses/$courseId/people'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdPeopleRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRouteRoute
    }
    '/_authenticated/courses/$courseId/progress': {
      id: '/_authenticated/courses/$courseId/progress'
      path: '/progress'
      fullPath: '/courses/$courseId/progress'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdProgressRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRouteRoute
    }
    '/_authenticated/courses/$courseId/quizzes': {
      id: '/_authenticated/courses/$courseId/quizzes'
      path: '/quizzes'
      fullPath: '/courses/$courseId/quizzes'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdQuizzesRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRouteRoute
    }
    '/_authenticated/courses/$courseId/rubrics': {
      id: '/_authenticated/courses/$courseId/rubrics'
      path: '/rubrics'
      fullPath: '/courses/$courseId/rubrics'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdRubricsRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRouteRoute
    }
    '/_authenticated/courses/$courseId/settings': {
      id: '/_authenticated/courses/$courseId/settings'
      path: '/settings'
      fullPath: '/courses/$courseId/settings'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdSettingsRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRouteRoute
    }
    '/_authenticated/courses/$courseId/syllabus': {
      id: '/_authenticated/courses/$courseId/syllabus'
      path: '/syllabus'
      fullPath: '/courses/$courseId/syllabus'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdSyllabusRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRouteRoute
    }
    '/_authenticated/courses/$courseId/assignments/': {
      id: '/_authenticated/courses/$courseId/assignments/'
      path: '/assignments'
      fullPath: '/courses/$courseId/assignments/'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdAssignmentsIndexRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRouteRoute
    }
    '/_authenticated/courses/$courseId/assignments/$assignmentId': {
      id: '/_authenticated/courses/$courseId/assignments/$assignmentId'
      path: '/assignments/$assignmentId'
      fullPath: '/courses/$courseId/assignments/$assignmentId'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdAssignmentsAssignmentIdRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRouteRoute
    }
    '/_authenticated/courses/$courseId/tools/$toolId': {
      id: '/_authenticated/courses/$courseId/tools/$toolId'
      path: '/tools/$toolId'
      fullPath: '/courses/$courseId/tools/$toolId'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdToolsToolIdRouteImport
      parentRoute: typeof AuthenticatedCoursesCourseIdRouteRoute
    }
  }
}

interface AuthenticatedCoursesCourseIdRouteRouteChildren {
  AuthenticatedCoursesCourseIdAnnouncementsRoute: typeof AuthenticatedCoursesCourseIdAnnouncementsRoute
  AuthenticatedCoursesCourseIdDiscussionsRoute: typeof AuthenticatedCoursesCourseIdDiscussionsRoute
  AuthenticatedCoursesCourseIdIgniteRoute: typeof AuthenticatedCoursesCourseIdIgniteRoute
  AuthenticatedCoursesCourseIdModulesRoute: typeof AuthenticatedCoursesCourseIdModulesRoute
  AuthenticatedCoursesCourseIdPeopleRoute: typeof AuthenticatedCoursesCourseIdPeopleRoute
  AuthenticatedCoursesCourseIdProgressRoute: typeof AuthenticatedCoursesCourseIdProgressRoute
  AuthenticatedCoursesCourseIdQuizzesRoute: typeof AuthenticatedCoursesCourseIdQuizzesRoute
  AuthenticatedCoursesCourseIdRubricsRoute: typeof AuthenticatedCoursesCourseIdRubricsRoute
  AuthenticatedCoursesCourseIdSettingsRoute: typeof AuthenticatedCoursesCourseIdSettingsRoute
  AuthenticatedCoursesCourseIdSyllabusRoute: typeof AuthenticatedCoursesCourseIdSyllabusRoute
  AuthenticatedCoursesCourseIdIndexRoute: typeof AuthenticatedCoursesCourseIdIndexRoute
  AuthenticatedCoursesCourseIdAssignmentsAssignmentIdRoute: typeof AuthenticatedCoursesCourseIdAssignmentsAssignmentIdRoute
  AuthenticatedCoursesCourseIdToolsToolIdRoute: typeof AuthenticatedCoursesCourseIdToolsToolIdRoute
  AuthenticatedCoursesCourseIdAssignmentsIndexRoute: typeof AuthenticatedCoursesCourseIdAssignmentsIndexRoute
}

const AuthenticatedCoursesCourseIdRouteRouteChildren: AuthenticatedCoursesCourseIdRouteRouteChildren =
  {
    AuthenticatedCoursesCourseIdAnnouncementsRoute:
      AuthenticatedCoursesCourseIdAnnouncementsRoute,
    AuthenticatedCoursesCourseIdDiscussionsRoute:
      AuthenticatedCoursesCourseIdDiscussionsRoute,
    AuthenticatedCoursesCourseIdIgniteRoute:
      AuthenticatedCoursesCourseIdIgniteRoute,
    AuthenticatedCoursesCourseIdModulesRoute:
      AuthenticatedCoursesCourseIdModulesRoute,
    AuthenticatedCoursesCourseIdPeopleRoute:
      AuthenticatedCoursesCourseIdPeopleRoute,
    AuthenticatedCoursesCourseIdProgressRoute:
      AuthenticatedCoursesCourseIdProgressRoute,
    AuthenticatedCoursesCourseIdQuizzesRoute:
      AuthenticatedCoursesCourseIdQuizzesRoute,
    AuthenticatedCoursesCourseIdRubricsRoute:
      AuthenticatedCoursesCourseIdRubricsRoute,
    AuthenticatedCoursesCourseIdSettingsRoute:
      AuthenticatedCoursesCourseIdSettingsRoute,
    AuthenticatedCoursesCourseIdSyllabusRoute:
      AuthenticatedCoursesCourseIdSyllabusRoute,
    AuthenticatedCoursesCourseIdIndexRoute:
      AuthenticatedCoursesCourseIdIndexRoute,
    AuthenticatedCoursesCourseIdAssignmentsAssignmentIdRoute:
      AuthenticatedCoursesCourseIdAssignmentsAssignmentIdRoute,
    AuthenticatedCoursesCourseIdToolsToolIdRoute:
      AuthenticatedCoursesCourseIdToolsToolIdRoute,
    AuthenticatedCoursesCourseIdAssignmentsIndexRoute:
      AuthenticatedCoursesCourseIdAssignmentsIndexRoute,
  }

const AuthenticatedCoursesCourseIdRouteRouteWithChildren =
  AuthenticatedCoursesCourseIdRouteRoute._addFileChildren(
    AuthenticatedCoursesCourseIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedPluginsRoute: typeof AuthenticatedPluginsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRoute
  AuthenticatedCoursesCourseIdRouteRoute: typeof AuthenticatedCoursesCourseIdRouteRouteWithChildren
  AuthenticatedAccountAccessibilityRoute: typeof AuthenticatedAccountAccessibilityRoute
  AuthenticatedAccountAnnouncementsRoute: typeof AuthenticatedAccountAnnouncementsRoute
  AuthenticatedAccountEportfoliosRoute: typeof AuthenticatedAccountEportfoliosRoute
  AuthenticatedAccountFilesRoute: typeof AuthenticatedAccountFilesRoute
  AuthenticatedAccountNotificationsRoute: typeof AuthenticatedAccountNotificationsRoute
  AuthenticatedAccountPortfolioRoute: typeof AuthenticatedAccountPortfolioRoute
  AuthenticatedAccountProfileRoute: typeof AuthenticatedAccountProfileRoute
  AuthenticatedAccountQrRoute: typeof AuthenticatedAccountQrRoute
  AuthenticatedAccountSharedRoute: typeof AuthenticatedAccountSharedRoute
  AuthenticatedAgentChatIdRoute: typeof AuthenticatedAgentChatIdRoute
  AuthenticatedAgentActivityRoute: typeof AuthenticatedAgentActivityRoute
  AuthenticatedCanvasCanvasIdRoute: typeof AuthenticatedCanvasCanvasIdRoute
  AuthenticatedNotesNoteIdRoute: typeof AuthenticatedNotesNoteIdRoute
  AuthenticatedNotesGraphRoute: typeof AuthenticatedNotesGraphRoute
  AuthenticatedAgentIndexRoute: typeof AuthenticatedAgentIndexRoute
  AuthenticatedCanvasIndexRoute: typeof AuthenticatedCanvasIndexRoute
  AuthenticatedCoursesIndexRoute: typeof AuthenticatedCoursesIndexRoute
  AuthenticatedNotesIndexRoute: typeof AuthenticatedNotesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedPluginsRoute: AuthenticatedPluginsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudentRoute: AuthenticatedStudentRoute,
  AuthenticatedCoursesCourseIdRouteRoute:
    AuthenticatedCoursesCourseIdRouteRouteWithChildren,
  AuthenticatedAccountAccessibilityRoute:
    AuthenticatedAccountAccessibilityRoute,
  AuthenticatedAccountAnnouncementsRoute:
    AuthenticatedAccountAnnouncementsRoute,
  AuthenticatedAccountEportfoliosRoute: AuthenticatedAccountEportfoliosRoute,
  AuthenticatedAccountFilesRoute: AuthenticatedAccountFilesRoute,
  AuthenticatedAccountNotificationsRoute:
    AuthenticatedAccountNotificationsRoute,
  AuthenticatedAccountPortfolioRoute: AuthenticatedAccountPortfolioRoute,
  AuthenticatedAccountProfileRoute: AuthenticatedAccountProfileRoute,
  AuthenticatedAccountQrRoute: AuthenticatedAccountQrRoute,
  AuthenticatedAccountSharedRoute: AuthenticatedAccountSharedRoute,
  AuthenticatedAgentChatIdRoute: AuthenticatedAgentChatIdRoute,
  AuthenticatedAgentActivityRoute: AuthenticatedAgentActivityRoute,
  AuthenticatedCanvasCanvasIdRoute: AuthenticatedCanvasCanvasIdRoute,
  AuthenticatedNotesNoteIdRoute: AuthenticatedNotesNoteIdRoute,
  AuthenticatedNotesGraphRoute: AuthenticatedNotesGraphRoute,
  AuthenticatedAgentIndexRoute: AuthenticatedAgentIndexRoute,
  AuthenticatedCanvasIndexRoute: AuthenticatedCanvasIndexRoute,
  AuthenticatedCoursesIndexRoute: AuthenticatedCoursesIndexRoute,
  AuthenticatedNotesIndexRoute: AuthenticatedNotesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  OauthGoogleReturnRoute: OauthGoogleReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
